Repository auth0/wordpress, pull requests merged in 2018-12, with the labels that each got.

#526 Spanish translation by Carlos Longarela
  languages/es_ES.mo
  languages/es_ES.po
Labels: CH: Added

#593 Added filter to allow for changing the output of die_on_login
  lib/WP_Auth0_LoginManager.php
Labels: CH: Added

#592 Move custom DB scripts to separate files
  WP_Auth0.php
  lib/WP_Auth0_Api_Operations.php
  lib/WP_Auth0_CustomDBLib.php
  lib/WP_Auth0_DBManager.php
  lib/scripts-js/db-get-user.js
  lib/scripts-js/db-login.js
  tests/testApiOperations.php
Labels: CH: Changed

#596 Whitelist Auth0 IPs by default and show in wp-admin
  WP_Auth0.php
  lib/WP_Auth0_DBManager.php
  lib/WP_Auth0_Ip_Check.php
  lib/WP_Auth0_Options_Generic.php
  lib/admin/WP_Auth0_Admin_Advanced.php
  lib/admin/WP_Auth0_Admin_Generic.php
  tests/testIpCheck.php
  tests/testWPAuth0DbMigrations.php
Labels: CH: Added

#600 Fix notice when settings constant is defined too late
  lib/WP_Auth0_Options_Generic.php
  phpcs-compat-ruleset.xml
  phpcs.xml.dist
  tests/testConstantSettings.php
  tests/testWPAuth0Options.php
Labels: CH: Fixed

#601 Allow subdomains in redirect and refactor validation tests
  lib/admin/WP_Auth0_Admin_Advanced.php
  tests/testAdvancedOptionsValidation.php
Labels: CH: Added

#604 Remove unnecessary callback; add notice if plugin is already setup
  lib/WP_Auth0_Api_Client.php
  lib/WP_Auth0_Settings_Section.php
  lib/initial-setup/WP_Auth0_InitialSetup_ConnectionProfile.php
  templates/initial-setup/connection_profile.php
Labels: CH: Changed
