Repository auth0/wordpress, pull requests merged in 2019-08, with the labels that each got.

#707 Add check for GET and POST globals for state validation
  lib/WP_Auth0_LoginManager.php
  tests/testLoginManagerInitAuth0.php
Labels: CH: Fixed, tiny

#706 Fix widget gravatar and language settings
  languages/wp-auth0-es_ES.mo
  languages/wp-auth0-es_ES.po
  languages/wp-auth0.pot
  lib/WP_Auth0_Lock10_Options.php
  lib/admin/WP_Auth0_Admin_Appearance.php
  templates/a0-widget-setup-form.php
Labels: CH: Fixed, small

#710 Release 3.11.1
  CHANGELOG.md
  WP_Auth0.php
  readme.txt
Labels: tiny

#709 Merge in released 3.11.1 version
  .circleci/config.yml
  CHANGELOG.md
  composer.json
  functions.php
  languages/wp-auth0-es_ES.mo
  languages/wp-auth0-es_ES.po
  languages/wp-auth0.pot
  lib/WP_Auth0_Embed_Widget.php
  lib/WP_Auth0_Ip_Check.php
  lib/WP_Auth0_Lock10_Options.php
  lib/WP_Auth0_LoginManager.php
  lib/admin/WP_Auth0_Admin_Advanced.php
  lib/admin/WP_Auth0_Admin_Appearance.php
  lib/admin/WP_Auth0_Admin_Basic.php
  lib/admin/WP_Auth0_Admin_Generic.php
  readme.txt
  templates/a0-widget-setup-form.php
  templates/back-to-auth0.php
  templates/initial-setup/connection_profile.php
  templates/initial-setup/connections.php
  templates/initial-setup/data-migration.php
  templates/initial-setup/rules.php
  tests/classes/WP_Auth0_Test_Case.php
  tests/testAdminBasicValidation.php
  tests/testConstantSettings.php
  tests/testEmbedWidget.php
  tests/testFunctionCanShowWpLoginForm.php
  tests/testIpCheck.php
  tests/testLoginManagerInitAuth0.php
  tests/testOptionClientId.php
  tests/testOptionClientSecret.php
  tests/testOptionDomain.php
  tests/testOptionLockCdn.php
  tests/testOptionMigrationIps.php
  tests/traits/wpDieHelper.php
Labels: tiny

#711 persist .snyk policy file
  .circleci/config.yml
Labels: tiny

#712 Remove feedback form from help tab
  languages/wp-auth0-es_ES.mo
  languages/wp-auth0-es_ES.po
  languages/wp-auth0.pot
  templates/settings.php
  webtask/ping.js
  webtask/slack-notifier.js
Labels: CH: Removed, tiny

#717 Add wpa0_user_data filter before creating WP_User
  lib/WP_Auth0_Users.php
Labels: CH: Added

#719 Remove unused setup wizard classes, methods, and templates
  languages/wp-auth0-es_ES.mo
  languages/wp-auth0-es_ES.po
  languages/wp-auth0.pot
  lib/initial-setup/WP_Auth0_InitialSetup.php
  lib/initial-setup/WP_Auth0_InitialSetup_Connections.php
  lib/initial-setup/WP_Auth0_InitialSetup_Migration.php
  lib/initial-setup/WP_Auth0_InitialSetup_Rules.php
  lib/initial-setup/WP_Auth0_InitialSetup_Signup.php
  templates/initial-setup/data-migration.php
  templates/initial-setup/rules.php
Labels: CH: Removed, tiny

#716 Update auth params method to add filters
  lib/WP_Auth0_LoginManager.php
  tests/testLoginManager.php
  tests/testLoginManagerAuthParams.php
Labels: CH: Changed, small
