Repository auth0/wordpress, pull requests merged in 2020-01, with the labels that each got.

#757 Remove future iat check
  lib/token-verifier/WP_Auth0_IdTokenVerifier.php
Labels: CH: Removed, review:tiny

#759 Add path to functions.php include
  .circleci/config.yml
  WP_Auth0.php
  bin/install-wp-tests.sh
Labels: CH: Fixed, review:tiny

#761 Release 3.11.2
  CHANGELOG.md
  WP_Auth0.php
  readme.txt
Labels: review:tiny

#762 Remove connection deactivation on setup
  lib/WP_Auth0_Api_Client.php
  lib/initial-setup/WP_Auth0_InitialSetup_Consent.php
  tests/testInitialSetupConsent.php
Labels: CH: Removed, review:small

#765 Remove custom signup fields setting
  lib/WP_Auth0_DBManager.php
  lib/WP_Auth0_Options.php
  lib/admin/WP_Auth0_Admin_Advanced.php
  lib/admin/WP_Auth0_Admin_Appearance.php
  templates/auth0-login-form.php
  tests/testWPAuth0DbMigrations.php
  tests/testWPAuth0Options.php
Labels: CH: Removed, review:small

#768 Fix potential XSS on wp-login.php override page
  WP_Auth0.php
Labels: CH: Security, review:tiny

#771 Change all redirects to wp_safe_redirect
  WP_Auth0.php
  lib/WP_Auth0_LoginManager.php
  lib/initial-setup/WP_Auth0_InitialSetup_AdminUser.php
  lib/initial-setup/WP_Auth0_InitialSetup_ConnectionProfile.php
  lib/initial-setup/WP_Auth0_InitialSetup_Connections.php
  lib/initial-setup/WP_Auth0_InitialSetup_Consent.php
  tests/testSafeRedirects.php
Labels: CH: Changed, review:small

#772 Remove screenshots and GH templates; update readme.txt
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  banner-1544x500.png
  banner-772x250.png
  icon-128x128.png
  icon-256x256.png
  readme.txt
  screenshot-1.png
  screenshot-2.png
  screenshot-3.png
  screenshot-4.png
  screenshot-5.png
Labels: review:tiny

#773 Adding advanced setting validation; normalize values throughout
  composer.json
  lib/WP_Auth0_Options.php
  lib/admin/WP_Auth0_Admin_Advanced.php
  lib/admin/WP_Auth0_Admin_Appearance.php
  lib/admin/WP_Auth0_Admin_Generic.php
  lib/initial-setup/WP_Auth0_InitialSetup_Consent.php
  tests/testLoginManagerRedirectLogin.php
  tests/testOptionMigrationWs.php
  tests/testRequiredEmail.php
  tests/testRoutesGetUser.php
  tests/testRoutesLogin.php
  tests/testUserRepoCreate.php
Labels: CH: Changed, review:small

#774 Update feature settings validation
  assets/css/initial-setup.css
  assets/css/initial-setup/main.styl
  lib/WP_Auth0_Options.php
  lib/admin/WP_Auth0_Admin_Features.php
  lib/admin/WP_Auth0_Admin_Generic.php
  tests/testLoginManager.php
  tests/testLoginManagerLogout.php
  tests/testOptionSlo.php
Labels: CH: Changed, review:small

#770 Add ability to break cache if RS256 ID token kid is not found
  lib/WP_Auth0_LoginManager.php
  lib/token-verifier/WP_Auth0_AsymmetricVerifier.php
  lib/token-verifier/WP_Auth0_JwksFetcher.php
  tests/testApiGetJwks.php
  tests/testJwksFetcher.php
  tests/testLoginManagerRedirectLogin.php
  tests/testOptionMigrationWs.php
  tests/testRoutesGetUser.php
  tests/testRoutesLogin.php
  tests/traits/tokenHelper.php
Labels: CH: Added, review:medium
