Repository auth0/wordpress, pull requests merged in 2021-02, with the labels that each got.

#814 Support PHP 8.0
  .circleci/config.yml
  WP_Auth0.php
  codecov.yml
  composer.json
  functions.php
  lib/WP_Auth0_Import_Settings.php
  lib/WP_Auth0_Ip_Check.php
  lib/WP_Auth0_LoginManager.php
  lib/WP_Auth0_Routes.php
  lib/WP_Auth0_UsersRepo.php
  lib/api/WP_Auth0_Api_Abstract.php
  lib/api/WP_Auth0_Api_Change_Email.php
  lib/api/WP_Auth0_Api_Change_Password.php
  lib/api/WP_Auth0_Api_Client_Credentials.php
  lib/api/WP_Auth0_Api_Exchange_Code.php
  lib/api/WP_Auth0_Api_Get_User.php
  lib/api/WP_Auth0_Api_Refresh_Access_Token.php
  lib/initial-setup/WP_Auth0_InitialSetup_AdminUser.php
  lib/initial-setup/WP_Auth0_InitialSetup_ConnectionProfile.php
  phpcs-test-ruleset.xml
  phpcs.xml.dist
  phpstan.neon.dist
  tests/phpstan/constants.php
  tests/phpstan/stubs.php
Labels: CH: Changed, review:small

#812 Add filters on user queries
  lib/WP_Auth0_UsersRepo.php
  tests/testUserRepoMeta.php
Labels: CH: Added

#819 Allow Composer installations w/ wpackagist
  composer.json
Labels: CH: Added, review:tiny

#820 Release 4.2.0
  CHANGELOG.md
  WP_Auth0.php
  readme.txt
Labels: review:tiny

#821 chore: Use standard MIT license format
  LICENSE
Labels: documentation, review:tiny
